### ISSUE TITLE
emojipasta.co down

### ISSUE THREAD

**Issue by aprivette** [Dallas-1/EmojiPastaGenerator#6]
Hello - I noticed the site is down the other day, is that intentional or no?

Thanks!

**Comment by JackDallas** [comment]
The server it was running on got shut off for a new thing, I think I can host it again on another one, the domain expires this month I think actually.

Let me have a look this weekend, this was pretty poorly wrote and I just made it when I was bored, I kinda fell out of love with JS maybe I'll throw together a v2 in Go or something then hook it up again

**Comment by aprivette** [comment]
That'd be interesting, I have the same feelings about node haha.  Super fun project though, I actually had it hooked up to a Slack slash command at my company which is why I asked.  I'll keep an eye on the domain though, thanks for letting me know!
![screen shot 2018-02-01 at 1 52 34 pm](https://user-images.githubusercontent.com/5871190/35697077-336f3c1a-0757-11e8-8ac4-12150c21e532.png)

**Comment by JackDallas** [comment]
Ahh wow that's really cool!! I have a bunch of downtime tommorow and did
need a reason to play with the net lib in go. I'll make sure the endpoints
are all the same if I can get it sorted shouldn't be too hard 🤔🤔

**Comment by aprivette** [comment]
Sweet - yea my coworkers had a good time with that thing lol.  Thanks!

**Comment by JackDallas** [comment]
https://github.com/JackDallas/EmojiPastaGenerator/issues/7 Ok new version is being tracked here :D
